version: '3.7'

services:
  django:
    image: django-test:latest
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    volumes:
      - .:/root/main
    ports:
      - "8000:8000"
