version: '3.7'


services:
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    container_name: docker_django_test
    image: docker_django_test:latest
#    volumes:
#      - .:./
    ports:
      - "8002:8002"


#services:
#  django:
#    restart: always
#    image: DOCKER_USERNAME/D_IMAGE_NAME
#    command: python manage.py runserver 0.0.0.0:8002
#    container_name: D_IMAGE_NAME
##    volumes:
##      - .:/root/main
#    ports:
#      - "8002:8002"

# DOCKER_USERNAME, D_IMAGE_NAME, D_IMAGE_NAME
