version: '3.7'


services:
  django:
    build: .
    restart: always
    image: sattorovdevops/docker_django_test
    command: python manage.py runserver 0.0.0.0:8002
    container_name: docker_django_test
#    volumes:
#      - .:/root/main
    ports:
      - "8002:8002"


#services:
#  django:
#    restart: always
#    image: DOCKER_USERNAME/D_IMAGE_NAME
#    command: python manage.py runserver 0.0.0.0:8002
#    container_name: D_IMAGE_NAME
##    volumes:
##      - .:/root/main
#    ports:
#      - "8002:8002"

# DOCKER_USERNAME, D_IMAGE_NAME, D_IMAGE_NAME
