name: Django project

run-name: "${{ github.actor }} ${{ github.event_name }}ed from ${{ github.ref_name }} branch"

on:
  push:
    branches:
      - main



jobs:
  deploy_to_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p ${{ github.event.repository.name }}/
            cd ${{ github.event.repository.name }}/
            git init
            git pull ${{secrets.REPO_URL}}
            
            docker compose down
            docker rmi $(docker compose images -a -q)
            docker-compose up -d
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "Send a notification to the channel"
        shell: python
        run: |
          import requests
          token = ${{ secrets.BOT_TOKEN }}
          token = "6973086969:AAGNWI_gjiRlQU8au9MTIMOliL6tYHAP-TQ"
          
          channel_id = ${{ secrets.CHANNEL_ID }}
          channel_id = "-1001990832664"
          
          event_name = str(${{ secrets.Repository_nane }})
          
          url = f"https://api.telegram.org/bot{token}/sendMessage?chat_id={channel_id}&text={event_name} worked successfully"
          
          requests.get(
              url=url
              )



#  DOCKER_USERNAME, D_IMAGE_NAME, DOCKER_PASSWORD

#  HOST, USERNAME, PRIVATE_KEY

#  REPO_URL
