name: Django project

run-name: "${{ github.actor }} ${{ github.event_name }}ed from ${{ github.ref_name }} branch"

on:
  push:
    branches:
      - main



jobs:
  deploy_to_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p ${{ github.event.repository.name }}/
            cd ${{ github.event.repository.name }}/
            git init
            docker images
            git pull ${{secrets.REPO_URL}}
            
            try {
            docker rmi -f ${{ secrets.D_IMAGE_NAME }}:latest
            } catch {
            echo "Not found docker image"
            }
            
            (
            docker rmi -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest
            ) || ( 
            echo "Not found docker compose"
            )

            docker compose down $(docker ps -a -q)
            docker-compose up -d

#            docker build -t ${{ secrets.D_IMAGE_NAME }}:latest .
#            docker tag ${{ secrets.D_IMAGE_NAME }}:latest  ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest
#            docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest


#  DOCKER_USERNAME, D_IMAGE_NAME, DOCKER_PASSWORD

# HOST, USERNAME, PRIVATE_KEY

# REPO_URL
