name: Django test project

run-name: Enter the latest changes in the project

on:
  push:
    branches:
      - main


jobs:
  push_to_dockerhub:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        if: success()
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy_to_server:
    needs: push_to_dockerhub
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.FOLDER_FOR_DEPLOYMENT }}/
            cd ${{ secrets.FOLDER_FOR_DEPLOYMENT }}/
            git init
            git pull ${{secrets.REPO_URL}}
            docker rmi -f ${{ secrets.D_IMAGE_NAME }}
            docker rmi -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest
            docker build -t ${{ secrets.D_IMAGE_NAME }} .
            docker tag ${{ secrets.D_IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.D_IMAGE_NAME }}
            docker compose down
            docker-compose up -d


#  DOCKER_USERNAME, D_IMAGE_NAME, DOCKER_PASSWORD

# FOLDER_FOR_DEPLOYMENT

# HOST, USERNAME, PRIVATE_KEY

# REPO_URL