name: Django deploy test

run-name: Access deploy

on:
  push:
    branches:
      - main
      - master



jobs:
  deploy:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd test_django/
            git pull ${{secrets.REPO_URL}}
            docker-compose down 
            docker-compose up --build -d
