name: Russian-language-teacher-bot

on:
  push:
    paths:
      - "**main.yml"
    branches:
      - master
      - developer

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up python version"
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.12'
      - name: "Pip install"
        run: python -m pip install --upgrade pip

      - name: "Create venv file"
        run: python3 -m venv venv

      - name: "Activate venv"
        run: source venv/bin/activate

      - name: "Install requirements.txt"
        run: pip install -r requirements.txt

      - name: "Let's see inside the venv file"
        run: pip freeze

      #      - name: "Create .env file"
      #        run: |
      #          touch .env
      #          echo "ADMINS=${{ secrets.ADMINS }}
      #          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      #          CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env

      #      - name: "Run bot"
      #        run: python app.py

      - name: "Get notify to admin"
        shell: python
        run: |
          import requests
          token = ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID = ${{ secrets.CHANNEL_ID }}
          event_name = str(${{ secrets.Repository_nane }})
          url = f"https://api.telegram.org/bot{token}/sendMessage?chat_id={CHANNEL_ID}&text={event_name} worked successfully"
          requests.get(
              url=url
              )
      - name: Message job1 status
        run: echo "### Job1 Done! :rocket:" >> $GITHUB_STEP_SUMMARY
